/*************************************************************************************
			       DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING
					   		     IMPERIAL COLLEGE LONDON 

 				      EE 3.19: Real Time Digital Signal Processing
					       Dr Paul Mitcheson and Daniel Harvey

				        		  LAB 3: Interrupt I/O

 				            ********* I N T I O. C **********

  Demonstrates inputing and outputing data from the DSK's audio port using interrupts. 

 *************************************************************************************
 				Updated for use on 6713 DSK by Danny Harvey: May-Aug 2006
				Updated for CCS V4 Sept 10
 ************************************************************************************/
/*
 *	You should modify the code so that interrupts are used to service the 
 *  audio port.
 */
/**************************** Pre-processor statements ******************************/

#include <stdlib.h>
//  Included so program can make use of DSP/BIOS configuration tool.  
#include "dsp_bios_cfg.h"

/* The file dsk6713.h must be included in every program that uses the BSL.  This 
   example also includes dsk6713_aic23.h because it uses the 
   AIC23 codec module (audio interface). */
#include "dsk6713.h"
#include "dsk6713_aic23.h"

// math library (trig functions)
#include <math.h>

// Some functions to help with writing/reading the audio ports when using interrupts.
#include <helper_functions_ISR.h>

//read the text file generated by Matlab into our program, 
//which contains the coefficient of the FIR filter in an array b[] and defines the number of coefficients as N.
#include "file_b.txt"

/******************************* Global declarations ********************************/

/* Audio port configuration settings: these values set registers in the AIC23 audio 
   interface to configure it. See TI doc SLWS106D 3-3 to 3-10 for more info. */
DSK6713_AIC23_Config Config = { \
			 /**********************************************************************/
			 /*   REGISTER	            FUNCTION			      SETTINGS         */ 
			 /**********************************************************************/\
    0x0017,  /* 0 LEFTINVOL  Left line input channel volume  0dB                   */\
    0x0017,  /* 1 RIGHTINVOL Right line input channel volume 0dB                   */\
    0x01f9,  /* 2 LEFTHPVOL  Left channel headphone volume   0dB                   */\
    0x01f9,  /* 3 RIGHTHPVOL Right channel headphone volume  0dB                   */\
    0x0011,  /* 4 ANAPATH    Analog audio path control       DAC on, Mic boost 20dB*/\
    0x0000,  /* 5 DIGPATH    Digital audio path control      All Filters off       */\
    0x0000,  /* 6 DPOWERDOWN Power down control              All Hardware on       */\
    0x0043,  /* 7 DIGIF      Digital audio interface format  16 bit                */\
    0x008d,  /* 8 SAMPLERATE Sample rate control             8 KHZ                 */\
    0x0001   /* 9 DIGACT     Digital interface activation    On                    */\
			 /**********************************************************************/
};

// Codec handle:- a variable used to identify audio interface  
DSK6713_AIC23_CodecHandle H_Codec;

 /******************************* Function prototypes ********************************/
void init_hardware(void);     
void init_HWI(void);         
void ISR_AIC(void);   
double non_circ_FIR(void);
double base_circ_FIR(void);
double symmetry_circ_FIR(void);
double doublesize_circ_FIR(void);

/******************************* Global Variables ***********************************/
/* Sampling frequency in HZ. Must only be set to 8000, 16000, 24000
32000, 44100 (CD standard), 48000 or 96000  */ 
int sampling_freq = 8000; 
/* Use this variable in your code to set the frequency of your sine wave 
   be carefull that you do not set it above the current nyquist frequency! */
float sine_freq = 1000.0;  
// set the sample as global variable such that its value can be observed easily in the watch table
Int16 samp;
//double x[N];//comment this line of code when using the fastest design, which is implemented by function 'doublesize_circ_FIR()'.
double x[2*N];//uncomment to use the fastest design
int i;
double output = 0.0;
int index = 0;
int index2 = N;//index2 will only be used in the fastest design, which is function 'doublesize_circ_FIR()'. 

/********************************** Main routine ************************************/
void main(){
  // initialize board and the audio port
  init_hardware();
  /* initialize hardware interrupts */
  init_HWI();
  /* loop indefinitely, waiting for interrupts */  					
  while(1)
  {};
}

/********************************** init_hardware() **********************************/  
void init_hardware()
{
    // Initialize the board support library, must be called first
    //it resets all the hardware to the default settings
    DSK6713_init();
    
    // Start the AIC23 codec using the settings defined above in config 
    //set the sampling frequency to 8K and the bit resolution to 16 bits
    H_Codec = DSK6713_AIC23_openCodec(0, &Config); 

	/* Function below sets the number of bits in word used by MSBSP (serial port) for 
	receives from AIC23 (audio port). We are using a 32 bit packet containing two 
	16 bit numbers hence 32BIT is set for receive */
	MCBSP_FSETS(RCR1, RWDLEN1, 32BIT);	

	/* Configures interrupt to activate on each consecutive available 32 bits 
	from Audio port hence an interrupt is generated for each L & R sample pair */	
	MCBSP_FSETS(SPCR1, RINTM, FRM);

	/* These commands do the same thing as above but applied to data transfers to  
	the audio port */
	MCBSP_FSETS(XCR1, XWDLEN1, 32BIT);	
	MCBSP_FSETS(SPCR1, XINTM, FRM);	
}

/********************************** init_HWI() **************************************/  
void init_HWI(void)
{
	IRQ_globalDisable();			// Globally disables interrupts
	IRQ_nmiEnable();				// Enables the NMI interrupt (used by the debugger)
	IRQ_map(IRQ_EVT_RINT1,4);		// Maps an event to a physical interrupt
	IRQ_enable(IRQ_EVT_RINT1);		// Enables the event
	IRQ_globalEnable();				// Globally enables interrupts
} 

/******************** WRITE YOUR INTERRUPT SERVICE ROUTINE HERE***********************/  
void ISR_AIC(void){	
	//mono_write_16Bit((Int16) (non_circ_FIR()));//write sample back to memory using non-circular convolution
											   //casting double into 16 bit int data type.
	//mono_write_16Bit((Int16) (base_circ_FIR()));//write sample back to memory using base circular convolution (no optimisation).
											    //casting double into 16 bit int data type.											    
	//mono_write_16Bit((Int16) (symmetry_circ_FIR()));//write sample back to memory using symmetry property of circular convolution
											   		//casting double into 16 bit int data type.												   		
	mono_write_16Bit((Int16) (doublesize_circ_FIR()));//write sample back to memory using double memory to implement circular convolution
											   		//casting double into 16 bit int data type.
											   		//this is the fastest design we implemented.	
}

/******************** NON-CIRCULAR FILTERING CODE CALLED BY A ISR***********************************/  
double non_circ_FIR(void){
//this function performs non-circular convolution
	samp = mono_read_16Bit();//read input and place in a 16 bit integer memory
	output = 0.0; //reset output to 0
	for(i=N-1; i>0; i--)
	{
		x[i] = x[i-1]; // move data along buffer from lower element to next higher
	}
	x[0] = (double) samp;// convert the new sample into double data type and put it into the buffer
	for(i=0; i<N; i++){  // convolution
		output += x[i]*b[i];// multiply accumulation
	}
	return output;
}
/******************** BASE-CIRCULAR FILTERING CODE CALLED BY A ISR***********************************/ 
double base_circ_FIR(void){
//this function performs basic circular convolution

    //the two for loops below avoids overflow/underflow of the index of x (index of x cell must lie in the range between 0 and N-1).
	//In this case, index is a global variable which is initially defined as 0. Thus avoids a problem of index being out of range.
    x[index] = (double) mono_read_16Bit();   //read input and store it in a buffer
	output = 0.0; //reset output
	//1st for loop loops from i=0 to i=(N-index-1) which is the point just before the overflow of the index of x. (index+i=N-1)
    for(i=0;i<N-index;i++){
        output += x[index+i]*b[i];
    }
    //This loop handles the overflow of the index of x and continues looping from i=(N-index+1) to i=N-1,
    //which is the end of the coefficient vector.
    for(i=N-index;i<N;i++){
        output += x[index-N+i]*b[i];
    }
    index--;//decrease index, therefore new input will be stored in decending order.
            // this instruction performs circular shift
    if(index == -1){index = N-1;}//note that N stands for the no. of elements in vector b[].
                             	// Therefore, the index for the last element is N-1.
    return output;
}
/******************** IMPROVEMENT ONE***********************************/
double symmetry_circ_FIR(void){
	x[index] = (double) mono_read_16Bit();//read input and store it into the buffer
	output = 0.0; //reset output
	if(index<N/2){//when underflow occurs in the right half of the buffers.
    	for(i=0;i<index;i++){ //avoid the attempt that right half of the buffer underflows.
                          	  //when i=index-1, x[index-i-1]=x[0] is at the margin of being below its range.
        	//MAC factorisation
        	output += (x[index+i] + x[index-i-1])*b[i];
    	}
    	for(i=index;i<N/2;i++){//N is even (214), for loop stops when i=(N/2)-1, and convolution completes.
        	//MAC factorisation
        	output += (x[index+i] + x[index-i+N-1])*b[i];
    	}
	}
	else{//when overflow occurs in the left half of the buffers.
    	for(i=0;i<N-index;i++){//avoid the attempt that left half of the buffer overflows.
                           	   //when i=N-index-1, x[index+i]=x[N-1] is at the margin of being below its range.
        	//MAC factorisation
        	output += (x[index+i] + x[index-i-1])*b[i];
    	}
    	for(i=N-index;i<N/2;i++){//N is even (214), for loop stops when i=N/2-1, and convolution completes.
                    //MAC factorisation
        	output += (x[index+i-N] + x[index-i-1])*b[i];
    	}
	}
	index--; //index decreases by 1 every time this function is called therefore the past inputs are stored in ascending order.
	if(index==-1){index=N-1;} //hanle underflow
	return output;
}
/******************** IMPROVEMENT TWO ***********************************/
double doublesize_circ_FIR(void){
	//read input and store it into a buffer
	x[index] = 2000*(double)mono_read_16Bit(); //store input in its first index
	x[index2] = x[index]; //store the input in its second index
						  //this is more efficient than reading input twice
	output = 0.0; //reset output
	//loop from first coefficient to the (N/2-1)th coefficient
	for(i=0;i<N/2;i++){
	    //factorised convolution using symmetry properties
	    output += b[i]*(x[index+i]+x[index2-i-1]);
	}
	index--; //decrease index
	if (index==-1){index=N-1;} //handle underflow
	index2 = index+N; //make index2 follow index
	output=output/2000;
	return output; //return output value.
}
