/*************************************************************************************
			       DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING
					   		     IMPERIAL COLLEGE LONDON 

 				      EE 3.19: Real Time Digital Signal Processing
					       Dr Paul Mitcheson and Daniel Harvey

				        		  LAB 3: Interrupt I/O

 				            ********* I N T I O. C **********

  Demonstrates inputing and outputing data from the DSK's audio port using interrupts. 

 *************************************************************************************
 				Updated for use on 6713 DSK by Danny Harvey: May-Aug 2006
				Updated for CCS V4 Sept 10
 ************************************************************************************/
/*
 *	You should modify the code so that interrupts are used to service the 
 *  audio port.
 */
/**************************** Pre-processor statements ******************************/
#include <stdlib.h>
//  Included so program can make use of DSP/BIOS configuration tool.  
#include "dsp_bios_cfg.h"
/* The file dsk6713.h must be included in every program that uses the BSL.  This 
   example also includes dsk6713_aic23.h because it uses the 
   AIC23 codec module (audio interface). */
#include "dsk6713.h"
#include "dsk6713_aic23.h"
// math library (trig functions)
#include <math.h>
// Some functions to help with writing/reading the audio ports when using interrupts.
#include <helper_functions_ISR.h>


/******************************* Global declarations ********************************/
/* Audio port configuration settings: these values set registers in the AIC23 audio 
   interface to configure it. See TI doc SLWS106D 3-3 to 3-10 for more info. */
DSK6713_AIC23_Config Config = { \
			 /**********************************************************************/
			 /*   REGISTER	            FUNCTION			      SETTINGS         */ 
			 /**********************************************************************/\
    0x0017,  /* 0 LEFTINVOL  Left line input channel volume  0dB                   */\
    0x0017,  /* 1 RIGHTINVOL Right line input channel volume 0dB                   */\
    0x01f9,  /* 2 LEFTHPVOL  Left channel headphone volume   0dB                   */\
    0x01f9,  /* 3 RIGHTHPVOL Right channel headphone volume  0dB                   */\
    0x0011,  /* 4 ANAPATH    Analog audio path control       DAC on, Mic boost 20dB*/\
    0x0000,  /* 5 DIGPATH    Digital audio path control      All Filters off       */\
    0x0000,  /* 6 DPOWERDOWN Power down control              All Hardware on       */\
    0x0043,  /* 7 DIGIF      Digital audio interface format  16 bit                */\
    0x008d,  /* 8 SAMPLERATE Sample rate control             8 KHZ                 */\
    0x0001   /* 9 DIGACT     Digital interface activation    On                    */\
			 /**********************************************************************/
};
// Codec handle:- a variable used to identify audio interface  
DSK6713_AIC23_CodecHandle H_Codec;


 /******************************* Function prototypes ********************************/
void init_hardware(void);     
void init_HWI(void);         
void ISR_AIC(void);   
double direct_implementation(void);
double directTwo_implementation(void);
double directTwo_Transposed_implementation(void);


/******************************* Global Variables ***********************************/
/* Sampling frequency in HZ. Must only be set to 8000, 16000, 24000
32000, 44100 (CD standard), 48000 or 96000  */ 
int sampling_freq = 8000; 
/* Use this variable in your code to set the frequency of your sine wave 
   be carefull that you do not set it above the current nyquist frequency! */
//float sine_freq = 1000.0;  
// set the sample as global variable such that its value can be observed easily in the watch table
Int16 samp;
int i;
double yout = 0.0;
double input = 0.0;
int count=0;

/*****************************lab5 direct_implementation*******************************/
/*
double a[] = {1, -0.8823529411764706};
double b[] = {0.0588235294117647, 0.0588235294117647};
int order = 1; //find the order of the filter
double x[]= {0, 0};
double y[]= {0, 0};
*/

/************************lab5 directTwo transposed and non-transposed*********************/
#include "coef.txt"//read the text file generated by Matlab 
					//which contains the coefficient of the FIR filter in an array b[] and 
					//defines the order number by Matlab using #define order
double step[order+1];



/********************************** Main routine ************************************/
void main(){
  // initialize board and the audio port
  init_hardware();
  /* initialize hardware interrupts */
  init_HWI();
  /* loop indefinitely, waiting for interrupts */  					
  while(1)
  {};
}

/********************************** init_hardware() **********************************/  
void init_hardware()
{
    // Initialize the board support library, must be called first
    //it resets all the hardware to the default settings
    DSK6713_init();
    
    // Start the AIC23 codec using the settings defined above in config 
    //set the sampling frequency to 8K and the bit resolution to 16 bits
    H_Codec = DSK6713_AIC23_openCodec(0, &Config); 

	/* Function below sets the number of bits in word used by MSBSP (serial port) for 
	receives from AIC23 (audio port). We are using a 32 bit packet containing two 
	16 bit numbers hence 32BIT is set for receive */
	MCBSP_FSETS(RCR1, RWDLEN1, 32BIT);	

	/* Configures interrupt to activate on each consecutive available 32 bits 
	from Audio port hence an interrupt is generated for each L & R sample pair */	
	MCBSP_FSETS(SPCR1, RINTM, FRM);

	/* These commands do the same thing as above but applied to data transfers to  
	the audio port */
	MCBSP_FSETS(XCR1, XWDLEN1, 32BIT);	
	MCBSP_FSETS(SPCR1, XINTM, FRM);	
}

/********************************** init_HWI() **************************************/  
void init_HWI(void)
{
	IRQ_globalDisable();			// Globally disables interrupts
	IRQ_nmiEnable();				// Enables the NMI interrupt (used by the debugger)
	IRQ_map(IRQ_EVT_RINT1,4);		// Maps an event to a physical interrupt
	IRQ_enable(IRQ_EVT_RINT1);		// Enables the event
	IRQ_globalEnable();				// Globally enables interrupts
} 

/******************** WRITE YOUR INTERRUPT SERVICE ROUTINE HERE***********************/  
void ISR_AIC(void){	
	//mono_write_16Bit(mono_read_16Bit());//test bare board response
										  //this will be measured by audio analyser and be subtracted 
	//mono_write_16Bit((Int16) (direct_implementation()));//write sample back to memory 
											   			//casting double into 16 bit int data type.										
	mono_write_16Bit((Int16) (directTwo_implementation()));//write sample back to memory 
											   			//casting double into 16 bit int data type.	
	//mono_write_16Bit((Int16) (directTwo_Transposed_implementation()));//write sample back to memory 
											   			//casting double into 16 bit int data type.
}

/******************** LAB 5 direct_implementation***********************************/
double direct_implementation(void){
 //this function works for any order number of IIR filter
 //this function implements direct form
 //it uses non-circular buffer, thus there is a potential enhancement
	samp = mono_read_16Bit(); //read from ADC and store the input into a 16bit int variable
	yout = b[0]*samp;//first coefficient multiplication
	for(i=order;i>0;i--){
		yout += x[i]*b[i]-y[i]*a[i]; //coefficients multiplication arithmetic
		y[i]=y[i-1]; //delay by shifting y[] buffer by one element 
		x[i]=x[i-1]; //delay by shifting y[] buffer by one element
	} 
	x[1] = samp; //x[1] is the buffer which stores current input
	y[1] = yout; //y[1] is the buffer which stores current output
	return yout;
}


/******************** LAB 5 directTwo_implementation***********************************/
double directTwo_implementation(void){
 //this function works for any order number of IIR filter
 //It implements direct form II non-transposed
 //it uses non-circular buffer, thus there is a potential enhancement, which will be seen in the next implementation
	step[0] = mono_read_16Bit();//read from ADC and store the input into a 16bit int variable
	yout = 0;//reset output before processing
	for(i=order; i>0; i--){
		step[0]-=a[i]*step[i];//multiplication accumulation of -a[] coefficients
		yout+=b[i]*step[i];//multiplication accumulation of b[] coefficients
		step[i]=step[i-1];//performs delay by shifting the buffer by one element
	}
	yout +=b[0]*step[0];//write the last multiply accumulation to the output
	return yout;
}


/******************** LAB 5 directTwo_Transposed_implementation**************************/
double directTwo_Transposed_implementation(void){
 //this function works for any order number of IIR filter
 //It implements direct form II transposed
 //it uses ncircular buffer, which significantly enhanced the code in terms of instruction cycles
	input = (double) (mono_read_16Bit()); //read from ADC, cast and store the input into a double variable
	yout = step[0] + b[0]*input;//write the output
	for(i=0; i<order-1; i++){
		step[i] = step[i+1] - a[i+1]*yout + b[i+1]*input;//sum of previous buffer and coefficients multiplications
	}
	step[order-1] = -a[order]*yout + b[order]*input;//writes the last buffer
	return yout;
}



